In [60]:
import numpy as np 
from PIL import Image 


def zoom_at(img, x, y, zoom):
    w, h = img.size
    zoom2 = zoom * 2
    img = img.crop((x - w / zoom2, y - h / zoom2, 
                    x + w / zoom2, y + h / zoom2))
    return img

#img_og=Image.open('./260812/260812_30mW_0mMol_Sync_rect_InterOpt/aaa_final_opt_mask.png')
#img_og=np.array(img_og)

#og_zoomed=zoom_at(img_og, 380,240, 10)

img_opt=Image.open('./260812/260812_30mW_0mMol_Sync_rect_TestOpt/aaa_final_opt_mask.png')
img_opt_np=np.array(img_opt)
w,h=img_opt.size
#img_opt=np.array(img_opt)

#og_zoomed.save('./260805/260805_30mW_0mMol_Stairs_Simulation/aaa_final_opt_mask_zoomed.png')
opt_zoomed=zoom_at(img_opt, 390,220, 40)
opt_cropped=img_opt.crop((w/2+70-5,h/2-50-5,w/2+70+5,h/2+5-50))
opt_cropped_np=np.array(opt_cropped)
print(opt_cropped_np)
np.savetxt('./260812/260812_30mW_0mMol_Sync_rect_TestOpt/aaa_final_opt_mask_cropped.txt',opt_cropped_np,fmt='%d')
np.savetxt('./260812/260812_30mW_0mMol_Sync_rect_TestOpt/fullmask.txt',img_opt_np,fmt='%d')
#opt_zoomed=np.array(opt_zoomed,dtype=np.uint8)
#print(opt_zoomed[16,16:])
opt_cropped
opt_cropped.save('./260812/260812_30mW_0mMol_Sync_rect_TestOpt/aaa_final_opt_mask_cropped.png')


[[  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0  13  53  41   0   0   0   0   0]
 [  0   0  53 165 176  47   0  20   6  15]
 [  0   0  41 176 255 255 235 255 216 201]
 [  0   0   0  47 255 255  27  92 138 116]
 [  0   0   0   0 235  27  15  15  15  15]
 [  0   0   0  20 255  92  15  15  31  15]
 [  0   0   0   6 216 138  15  30 115  61]
 [  0   0   0  16 201 116  15  15  61  15]]


In [27]:
from PIL import Image,ImageDraw
img=Image.open('./260812/images/teeth.png')
w,h=img.size
box1=(80,45,w//2-80,h//2-45)
box2=(w//2+80,45,w-80,h//2-45)
box3=(80,h//2+45,w//2-80,h-45)
box4=(w//2+80,h//2+45,w-80,h-45)
img1=img.crop(box1)
img2=img.crop(box2)
img3=img.crop(box3)
img4=img.crop(box4)
img1.save('./260812/images/teeth_1.png')
img2.save('./260812/images/teeth_2.png')
img3.save('./260812/images/teeth_3.png')
img4.save('./260812/images/teeth_4.png')